name: Dependabot Auto Approve & Merge on Successful Build

on:
  workflow_run:
    workflows: ["Validate React Build on PR"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only run if the build workflow passed and the associated PR is from Dependabot
    if: >
      ${{ 
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.pull_requests &&
        github.event.workflow_run.pull_requests[0].user.login == 'dependabot[bot]'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Approve Dependabot PR
        run: |
          gh pr review --approve "${{ github.event.workflow_run.pull_requests[0].number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_MERGE_TOKEN }}

      - name: Merge Dependabot PR
        run: |
          # You can use --auto if you want GitHub to wait for branch protection checks,
          # or remove it to merge immediately.
          gh pr merge --squash "${{ github.event.workflow_run.pull_requests[0].number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_MERGE_TOKEN }}
